# .github/workflows/android-ci.yml

name: Android CI Build
# ... (все предыдущие шаги остаются без изменений) ...

    # Шаг 6: Сборка APK
    - name: Build with Gradle
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run: ./gradlew assembleDebug

    # =================================================================
    #           НОВЫЙ ШАГ ДЛЯ ДИАГНОСТИКИ МАНИФЕСТА
    # =================================================================
    - name: Print Merged Manifest
      run: |
        echo ">>>>>> Final AndroidManifest.xml that went into the APK:"
        cat app/build/intermediates/packaged_manifests/debug/AndroidManifest.xml
        echo ">>>>>> End of Manifest"
    # =================================================================

    # Шаг 7: Загрузка APK как артефакта
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk
